version: '3.8'

services:
  hbbs:
    container_name: rustdesk-hbbs
    image: rustdesk/rustdesk-server:1.1.12
    command: hbbs -r remote.zapprovedor.com.br:21117
    volumes:
      - ./data:/root
    network_mode: host
    restart: always
    environment:
      - RUST_LOG=info
      - ALWAYS_USE_RELAY=Y

  hbbr:
    container_name: rustdesk-hbbr
    image: rustdesk/rustdesk-server:1.1.12
    command: hbbr
    volumes:
      - ./data:/root
    network_mode: host
    restart: always
    environment:
      - RUST_LOG=info

  rustdesk-api:
    container_name: rustdesk-api
    image: lejianwen/rustdesk-api:latest
    volumes:
      - ./api-data/conf:/app/conf
      - ./api-data/data:/app/data
      - ./api-data/runtime:/app/runtime
      - ./data:/data:ro
    network_mode: host
    depends_on:
      - hbbs
      - hbbr
    restart: always

networks:
  rustdesk-net:
    driver: bridge
